### PR TITLE
Enable all UART ports for pine64

### PR DESCRIPTION
**Pull request by whongx**
I have try to enable all UART ports for pine64 so that users don't need to enable the port again when they needed it. All the files under boot/pine64 are generated from your scripts. Thank you!

### CODE REVIEW

**Comment by ayufan** [comment]
@whongx Can you remove binaries? I will update them myself.

**Comment by whongx** [comment]
@ayufan Done!

**Comment by ayufan** [comment]
@whongx Remove from these changes, not remove totally. I only need changes to `sys_config`.

**Comment by ayufan** [comment]
Hmm. I should see only `sys_config` change, but you modify the files. Can you squash all changes into the single commit? and make sure that diff only contains `sys_config`?

Maybe it will be easier to create a new pull request. Otherwise `git merge --squash` can help.

**Comment by whongx** [comment]
Hi, i think i would create a new pull request. So do this pull request can be deleted? Sorry for any inconvenience.

**Comment by ayufan** [comment]
Yes. I will close it.

**Pull request closed without merging**
