### PR TITLE
Update bootlogo for Pinebook

### PR DESCRIPTION
**Pull request by whongx**

### CODE REVIEW

**Comment by ayufan** [comment]
@whongx please do `ayufan` lowercase, maybe we should also include some link to troubleshooting?

**Comment by whongx** [comment]
@ayufan Hi, what do you mean please do ayufan lowercase?

**Comment by ayufan** [comment]
Looking at nicknames at irc and forum:
- ayufan
- longsleep
- Xalius
- Icenoway
- lukasz

I think that we should preserve casing :)

**Comment by ThomasKaiser** [comment]
> Icenoway

Icenowy please :)

**Comment by whongx** [comment]
Ok. Noted!

**Comment by ayufan** [comment]
Oh. Right. Icenowy. We should also include tkaiser :)

**Comment by ThomasKaiser** [comment]
> We should also include tkaiser :)

No, please. I'm fine contributing here and there without being mentioned.

**Pull request merged**
